version: '3.4'
services:
    db:
        image: dolthub/dolt-sql-server
        ports:
        - 3306
        volumes:
        - ./db/sql:/docker-entrypoint-initdb.d
    py-srv:
        build: py-srv
        command: python app.py
        ports:
        - '8000'
        labels:
        - traefik.enable=true
        - traefik.http.routers.myapp.tls=true
        - traefik.http.routers.myapp.rule=Host("myapi.docker.localhost")
    traefik:
        image: traefik:v2.4
        container_name: traefik
        labels:
        - traefik.enable=true
        - traefik.http.routers.traefik=true
        ports:
        - 443:443
        - 8080:8080
        volumes:
        - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
        - ./traefik/config.yml:/etc/traefik/config.yml:ro
        - ./traefik/cert:/etc/certs:ro
        - /var/run/docker.sock:/var/run/docker.sock:ro
